swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API

paths:
  /log/region:
    get:
      summary: gets region
      operationId: app.get_offset_region
      produces:
      - application/json
      parameters:
      - in: query
        name: offset
        required: true
        type: integer
      responses:
        200:
          description: returns region
          schema:
            type: array
            items:
              $ref: '#/definitions/Region'
        400:
          description: error
          
  /log/roast:
    get:
      summary: gets oldest roast
      operationId: app.get_oldest_roast
      description: Returns oldest roast
      produces:
      - application/json
      responses:
        200:
          description: returns roasts
          schema:
            type: array
            items:
              $ref: '#/definitions/Roasts'
        400:
          description: error

definitions:
  Region:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Ethiopia

  Roasts:
    type: object
    required:
    - id
    - name
    - region
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: fdhsajkl
      region:
        type: string
        example: ethiopia